---
title: Intro to Game Theory
author: Connor T. Wiegand
format: 
   revealjs:
      theme: serif
      preview-links: true
      chalkboard: false
      slide-number: true
      menu:
         side: right
      scrollable: true
      smaller: true
      incremental: true
      slide-level: 3
   # html:
      # embed-resources: true
   # pdf
# editor:
#    render-on-save: true
---

### Game

- Partner up

- Determine who is player 1 & who is player 2
   - age
   - voice pitch
   - last name

---

- Player 1 is the _dictator_, while player 2 is the _ultimator_

- The dictator has $100. They can choose an amount $a\in[0,100]$ which they can give to the ultimator, keeping the rest for themself.
   - ex: if I am the dictator, \$46 $\sim$ I keep \$53, while my partner receives \$46. 

- This constitutues the moves player 1 has

- The ultimator has only 2 moves: _yes_ and _no_. 
   - [yes]: both players walk away with the dollar amounts specified by player 1
   - [no]: both players leave with **$0**

- Go

### 

What do you notice?

- ...now switch

- <!-- New outcomes -->

## Course info

### About me

### Syllabus

### Course Administration

      ## New Game

### 2/3 Average Game

- Your moveset: pick any number $x\in[0,100]$

- Your goal: be as close to the target number as possible

- The target number...
   1. Label each player's guess as $x_i$

   2. Compute the average guess, $\overline{x}$ (For $n$ players: $\sum_{i=1}^{n} x_i$)

   3. Let $T=\frac{2}{3}\overline{x}$

- That is, the target number is 2/3 of the average of the guesses from all players

- Now, submit your guesses by ??? emailing me at [cwiegand@uoregon.edu](mailto:cwiegand@uoregon.edu)

### Go!

```{r 2-3_avg}
x_vec <- c()
# replace (?<=\d)\s+?(?=\d) with `$1:space:`
x_bar <- mean(x_vec)

tar <- (2/3) * x_bar
tar
```






