project:
  title: "ec327-sp24"

format: 
  revealjs: 
    theme:
      - lecture-slides/sp24-slides.scss ## Term-specific theme for slides
      - qSlides.scss ## Very basics (fonts, title-slide,) 
      # - ./deck-n.scss ## doc-specific mods to theme
    slide-number: true
    menu:
      side: right
    smaller: true
    incremental: true
    preview-links: true





