---
title: Nash Equilibria
author: "[with]{.with} Connor T. Wiegand"
format: 
   revealjs:
      slide-level: 3
      chalkboard: true
         # src: imgs/chalkboard.json
      # embed-resources: true
# editor:
#    render-on-save: true
---

## Best Responses

### Last time

- We got a mathy def. of best responses

- ...

- Function vs. Correspondence

- [Some comments on choice in mathematics](#sec-mathabs)

- What does it mean?

### Visualization of $BR(\cdot)$

- a

<!-- sketch of a set-values plot -->

- In words: the Best response function
   - Takes a particular strategy profile _from your opponents' strategies_ as an input
   - Spits out your best response

- What is a "best response"?
   - something that's at least as good as anything else you can do, _given the same input_

- put 2 + 2 together
   - Your best response function takes an opponents' strategy [profile] as an input, and outputs a subset of your strategies which are at least as good as all the others, if not better. 
   - E.g.
   <!-- def -->

### Recall: Best Response Definition {#sec-br-def}

A [**Best Response Correspondence**]{.alert} (or [function]{.hi}) is a map for player $i$,
   
$$BR{i}: S_{-i}\to S_{i}$$

such that, if $s_{i}^{BR}\in BR_{i}(s_{-i})$ (resp. [$s_{i}^{BR}= BR_{i}(s_{-i})$]{.hi})

then 

$$\pi_{i}(s_{i}^{BR}, s_{-i})\ge \pi_{i}(s_{i}', s_{-i})$$

for all $s_{i}'\in S_{i}$

### Pop Quiz

- T or F: Given some collection of opponents' strategies $\hat{s}$, the payoff for any one strategy in $BR_{i}(\hat{s})$ is the same as the payoff for any other strategy in $BR_{i}(\hat{s})$.


### 

[]()


### 

[]()



## Nash Equilibria --  Math


### To an equilibrium

1. [**Def**]: A [Nash Equilibrium]{.hii} is a set^[or _intersection_] of mutual Best Responses
   - E.g., a strategy profile is a [NE]{.hi} provided that all players are best responding to the other players' moves

2. Mathematically,

   - $s^{*}=(s_{1}^{*},\dots,s_{n}^{*})$ is a [NE]{.hi} if, $\forall i$, 

      $$\pi_{i}(s_{i}^{*}, s_{-i}^{*})\ge \pi_{i}(s_{i}', s_{-i}^{*})$$

      for any $s_{i}'\in S_{i}$

- [Compare to Best Response def](#sec-br-def)

### NE (cont.)

3. A strategy profile $s^{*}=(s^{*}_{1},\dots,s^{*}_{n})$ is a [NE]{.hi} provided that no player can unilaterally deviate from their strategy $s_{i}^{*}$ an receive a strictly better payoff (holding all other players' moves fixed)

- Aside: an equilibrium is [**always**]{.ul .alert} a strategy profile, [not]{.ul} a payoff (or payoff tuple)

### PD

[](tex-games/PD.tex)

### Dominance and NE

- Recall the Iterated Deletion Method:\\
   - IDSDS never eliminates a ~~good prediction~~ [NE]{.hi}
   - If a unique strategy profile survives IDSDS, then it is the unique ~~good prediction~~ Nash equilibrium for the game

## Nash Equilibria -- Solving

### Idea

- To help us keep track of best responses, we can simply underline the payoffs which correspond to best responses

### 

[]()

###

[]()

###

[]()



### Matching Pennies

[](Matching Pennies)

### Food for thought

- What if players did not play every game the same way?
   - Think of Rock, Paper, Scissors

- Abstracting away from _how_ our opponent may make a randomized^[or _stochastic_] decision, let's simply model their strategy according to the probability that they select each of their moves

- E.g. $$ p_{H}H + p_{T}T $$

- This generates two new questions for us
   - What are probabilities are reasonable to play?
   - Why would someone play such a strategy?

## Appendix

### Abstraction in Math {#sec-mathabs}

- Arbitrary

- $\forall$ (For all)

- Instantiation


{{{
### Never Best Responses

- [Def]{.def} [[Version 1.0]]: 

- How is this related to strict/weak domination?

### Ex

[]()

- $x \succsim_{W} y$ for _____
   - and y is NBR

- $z$ is not dominated by anything for ____
   - but $z$ is still NBR

### Never Best Responses

:::{.nonincremental}
- [Def]{.def} [[Version 1.0]]: 

- How is this related to strict/weak domination?
:::

- [**Fact:**]{.alert} a strictly dominated strategy is never a best response
   - Proof:

- [_Remark_]{.alert} we will return to this later
}}}


## Next time

### Recall: BRs and NE

[]()

<!-- ## Mixed Strategies -->

### Matching Pennies

### Probabilistic Strategies

- Such a strategy is called a [Mixed Strategy]
- Contrast to Pure strategies -- what we have been discussing thus far
   - $s_{i}\in S_i$ denotes a pure strategy in a player's space of pure strategies
   - $\sigma_{i}(\cdot)\in \Sigma_{i}$ denotes a mixed strategy in a player's space of mixed strategies
- Mixed 

### When will I play a mixed strategy?

### Theorem

### How do we find MSNE?

- It's complicated...we'll return to this later

- For now, I primarily want you to know when/why players mix and Nash's theorem