---
title: Introduction to Game Theory
author: "[with]{.with} Connor T. Wiegand"
format: 
   revealjs:
      theme: 
         - ../sp24-slides.scss ## Term-specific theme for slides
         - ../../qSlides.scss ## Very basics (fonts, title-slide,) 
  
         # - ./deck-n.scss ## doc-specific mods to theme
      preview-links: true
      chalkboard: false
      slide-number: true
      menu:
         side: right
      smaller: true
      incremental: true
      slide-level: 3
      # embed-resources: true
editor:
   render-on-save: true
---

## What's in a Game?

### From last time...

### Players

- Agents, users, etc. 

- To be a proper game, there should be <u> at least two </u> players

- Consider the following example:

   <!--
      2 player ex. where 1 player is practially useless
   -->

- This is something we might think of as a "game", but is really just a decision with some [exogeneity]{.hi}^[exogenous = 'falls from the sky'] from the environment

- Having two or more _real_ players is sometimes known as "strategic interaction"

### Strategies

- AKA
   - Moves
   - Actions

- What choices the player has 

- For now, the above terms can be treated as identical. 

- Later, when we introduce imperfect information, we will consider 

. . . 

::::::{.columns}

:::{.column width="15%"}

#### Moves

- informal
- colloquial
- general
:::

:::{.column width="45%"}

#### Strategies

- Technical
- Precise

- <u> **Def:** </u>

   _an information-contingent plan of action_
:::

:::{.column width="40%"}
#### Actions

- The components of a strategy
   - ...typically for each info. set
:::
::::::

### Payoffs

- Crucial to economics

- The utility (or payoff*) obtained from a specific outcome in a game

   - (outcome = result of each player playing a pre-determined **strategy**)

<!-- * $u(\cdot)$ vs. $\pi(\cdot)$ (maybe) -->

## EC 301 Review

### Agents, utility, etc. 

## Assumptions in Game Theory

### Assumptions

- Let game $G$ be composed of players [you]{.pl1} and [I]{.pl2}

<!-- no clue -->
- _Rules of the game_:

1. I know the rules of the game

::: {.fragment fragment-index=3}
   - I know that you know the rules of the game
:::

   - I know that you know that I know the rules of the game


   - I know that you know that I know that you know the rules of the game

   - ...

::: {.fragment fragment-index=2}

1. You know the rules of the game

:::

::: {.fragment fragment-index=4}

   - You know that I know the rules of the game
:::

   - You know that I know that you know the rules of the game

   - You know that I know that you know that I know the rules of the game

   - ...

   <!-- need some examples!  -->

### Common Knowledge of RotG

Let $\Gamma$ be a game with players $P_1,\dots,P_k$

Assumption 1: Common Knowledge of the Rules of the Game

- Every Statement of the form "Player $i$ knows that player $j$ knows that ... player $k$ knows the rules of the game" is true.

. . .

:::{style="margin-left: 25%;"}
{{< video https://www.youtube.com/embed/98TQv5IAtY8?si=8W3TkARkYYBKxrvb width="612" height="378" >}}
:::

:::{aside}
[Blue Eyed Islander Problem -- backup](https://www.youtube.com/watch?v=98TQv5IAtY8) 
:::

### Assumptions, cont.

1. Common Knowledge of the Rules of the Game

2. Common Knowledge of **Rationality**

   a. I am rational
      - I know that you are rational
      - I know that you know that I am rational
      - ...
   b. you are rational
      - You know that I am rational
      - You know that I know that you are rational
      - ...

. . .


[... but what is rationality?]{.bottom}

### Rationality

What is it?

- ~~Players maximize their expected payoffs~~

Technically speaking, rational agents (agents with rational preferences) are those who exhibit preferences which satisfy both of:

1. Completeness

2. Transitivity

### Preferences

Wait, what?

1. Completeness:

   - [Def]{.def} Given $x,y\in X$, an agent's preferences are **complete** provided at least one of the following is true:
      - $x\succsim y$
      - $y \succsim x$

   - [Ex.]

\

2. Transitivity:

   - [Def]{.def} Given $x, y, z\in X$, suppose that $x\succsim y$ and $y\succsim z$. Under these conditions, an agent's preferences are **transitive** provided that $x\succsim z$

   - [Ex.]


### Assumptions

...so...?

- We assume agents' preferences follow the classical assumptions of microeconomics...
   - (Players maximize their expected payoffs)

1. Common Knowledge of the Rules of the Game

2. Common Knowledge of Rationality

- and that's it!


## Math Review

### Logic Review

### Symbols

### Mathematical Techniques


## Extra Slides

### Extra Slide 1

### Extra Slide 2

### Extra Slide 3

### Extra Slide 4

### Extra Slide 5