---
title: Games in Normal Form
author: "[with]{.with} Connor T. Wiegand"
format: 
   revealjs:
      slide-level: 3
      chalkboard: true
         # src: imgs/chalkboard.json
      # embed-resources: true
# editor:
#    render-on-save: true
---

## Names

## IDSDS

### Recall

- Recall common knowledge assumptions

- If both players know the rules of the game, they can both work out dominated strategies

- Rational players won't play dominated strategies

- Idea: once both players figure this out, they should just _remove the dominated strategy from the game_

### Example^[slightly modified since last time]

::::::{.columns}
::::{.r-stack .column}
:::{.fragment .fade-out .absolute right="10"}
[](tex-games/ex1-4x4-v0.tex)
:::

:::{.fragment .absolute fragment-index=2 right="10"}
[](tex-games/ex1-4x4-v1.tex)
:::
::::

::::{.column width=60%}
:::{.nonincremental .fragment fragment-index=2}
- Recall that we said $C\succ_{D}B$ for Tim
:::

:::{.nonincremental .fragment fragment-index=3}
- Given that both players know this, we should simply proceed as if that row weren't there
:::
::::
::::::

### Example (cont.)

::::::{.columns}
::::{.r-stack .column}
:::{.fragment .fade-out .absolute right="10"}
:::{.fragment .fade-out fragment-index=3}
[](tex-games/ex1-3x4-v0.tex)
:::
:::

:::{.fragment .absolute fragment-index=3 right="10"}
[](tex-games/ex1-3x4-v1.tex)
:::
::::

::::{.r-stack}
:::{.fragment .absolute fragment-index=4 right="65" bottom="100"}
[](tex-games/ex1-3x3-v0.tex)
:::

:::{.fragment .absolute fragment-index=6 right="65" bottom="100"}
[](tex-games/ex1-3x3-v1.tex)
:::

:::{.fragment .absolute fragment-index=7 right="65" bottom="93"}
[](tex-games/ex1-3x3-v2.tex)
:::
::::

::::{.column width=60%}
:::{.nonincremental .fragment fragment-index=1}
- Now what do we notice?
:::

:::{.nonincremental .fragment fragment-index=2}
- Since both players know that Tim will never rationally play $B$, 
   - [$Z\succ_{D} Y$]{.pl2} for Eric [(in the reduced game)]{.go}
:::

:::{.nonincremental .fragment fragment-index=3}
- ...so let's eliminate it!
:::
\

\

:::{.nonincremental .fragment fragment-index=5}
- Now what?
   - Rinse and repeat
:::

:::{.nonincremental .fragment fragment-index=6}
- Now  [$C\succ_{D} A$]{.pl1} for Tim
:::

:::{.nonincremental .fragment fragment-index=7}
- Given this,  [$X\succ_{D} W$]{.pl2} for Eric
:::

::::
::::::

### Take it back now y'all




### Theorem

**Lemma:**

- IDSDS never eliminates a "good prediction"
   - keep this in mind for the homework

. . .

**Theorem:**

- If a [unique]{.ul} strategy profile survives IDSDS, then it is the unique "good prediction" for the game

. . .

**Corollary:**

- When performing IDSDS, order of operations does not matter
   - Sometimes, there is only one order you can go in
   - Sometimes, there are many...as long as you are following the rules of IDSDS, it doesn't matter which you choose!

- Given this last theorem, make sure to [**clearly**]{.alert} list the order in which you are eliminating
   - In addition to being clear about which strategy you are eliminating...
   - ...for which player...
   - ...and why
