---
format: 
   pdf: 
      documentclass: scrartcl
      papersize: letter
      fontsize: 15pt
      pdf-engine: pdflatex
      # latex: 
      include-in-header: 
         - text: |
            \usepackage{sgamex}
            \usepackage{mathtools}
            
# format: pdf
---


\newcommand{\rc}[1]{\color{red}{#1}}
\newcommand{\bc}[1]{\color{blue}{#1}}

\begin{figure}\hspace*{\fill}%
   \begin{game}{2}{2}[$A$][$B$]
      & Remain & Swerve\\
      Stand Ground & $-\infty, -1000$ & $100, 0$\\
      Roll Dodge & $-5, 20$ & $-10, -10$
   \end{game}
\hspace*{\fill}%
\end{figure}



\begin{figure}\hspace*{\fill}%
\renewcommand{\gamestretch}{1.3}
   \begin{game}{2}{2}[$P_1$][$P_2$]
      & L & R\\
      T & $\pi_1(T,L),\, \pi_2(T,L)$ & $\pi_1(T,R),\, \pi_2(T,R)$\\
      B & $\pi_1(B,L),\, \pi_2(B,L)$ & $\pi_1(B,R),\, \pi_2(B,R)$
   \end{game}
\hspace*{\fill}%
\end{figure}


\begin{figure}\hspace*{\fill}%
   \begin{game}{2}{2}[\textbf{K}rabs][\textbf{P}lankton]
      & $S$ & $Q$\\
      $S$  & $-5, -5$ & $-1, -10$\\
      $Q$  & $-10, -1$ & $-2, -2$
   \end{game}
\hspace*{\fill}%
\end{figure}

\begin{figure}\hspace*{\fill}%
   \begin{game}{2}{2}[A][B]
      & $F$ & $B$\\
      $F$  & $3, 1$ & $1, 1$\\
      $B$  & $0, 0$ & $2, 3$
   \end{game}
\hspace*{\fill}%
\end{figure}

\begin{figure}\hspace*{\fill}%
\begin{game}{2}{2}[$P_1$][$P_2$]
& $x$ & $y$\\
$a$ & $2,2$ & $100,35$\\
$b$ & $3,0$ & $350,16$
\end{game}
\hspace*{\fill}%
\end{figure}

\begin{figure}\hspace*{\fill}%
\begin{game}{2}{2}[\rc{$P_1$}][\bc{$P_2$}]
& $x$ & $y$\\
$a$ & $2,2$ & $100,35$\\
$b$ & $3,0$ & $350,16$
\end{game}
\hspace*{\fill}%
\end{figure}

\begin{figure}\hspace*{\fill}%
\begin{game}{2}{2}[$P_1$][$P_2$]
& \bc{$x$} & \bc{$y$}\\
\rc{$a$} & $2,2$ & $100,35$\\
\rc{$b$} & $3,0$ & $350,16$
\end{game}
\hspace*{\fill}%
\end{figure}

\begin{figure}\hspace*{\fill}%
\begin{game}{2}{2}[$P_1$][$P_2$]
& $x$ & {$y$}\\
{$a$} & $\rc{2},\bc{2}$ & $\rc{100},\bc{35}$\\
{$b$} & $\rc3,\bc0$ & $\rc{350},\bc{16}$
\end{game}
\hspace*{\fill}%
\end{figure}
