---
title: Introduction to Game Theory
author: "[with]{.with} Connor T. Wiegand"
format: 
   revealjs:
      theme: 
         - ../../sp24-slides.scss ## Term-specific theme for slides
         - ../../../qSlides.scss ## Very basics (fonts, title-slide,) 
  
         # - ./deck-n.scss ## doc-specific mods to theme
      preview-links: true
      chalkboard: false
      slide-number: true
      menu:
         side: right
      smaller: true
      incremental: true
      slide-level: 3
      embed-resources: true
# editor:
#    render-on-save: true
---

### Game Time

- Partner up

- Determine who is player 1 & who is player 2

   - age
   - alphabetical by middle name
   - reverse alphabetical last name

- Player 1 is the _dictator_, while player 2 is the _ultimator_

- The dictator has $100. They can choose an amount $a\in[0,100]$ which they can give to the ultimator, keeping the rest for themselves.
   - ex: if I am the dictator, "\$46" $\rightarrow$ "I keep \$54, while my partner receives $46"

- This constitutes player 1's moves

- The ultimator has only 2 moves: _yes_ and _no_. 
   - [yes]{.hii}: both players walk away with the dollar amounts specified by player 1
   - [no]{.hii}: both players leave with _$0_

- [_Go_]{.hi}

### What do you notice?



[...now switch]{.fragment .absolute fragment-index=2 bottom="10"}

### Now what do we notice?
<!-- Empty on purp. -->

## Course info

### Syllabus {.f1}

\ 

- [Link to Canvas File]("https://canvas.uoregon.edu/courses/240139/files/folder/Syllabus?preview=18683456")


## New Game

### 2/3 Average Game

- Your moveset: pick any number $x\in[0,100]$

- Your goal: be as close to the target number as possible

- The target number...
   1. Label each player's guess as $x_i$

   2. Compute the average guess, $\overline{x}$ (For $n$ players: $\sum_{i=1}^{n} x_i$)

   3. Let $T=\frac{2}{3}\overline{x}$

- That is, the target number is 2/3 of the average of the guesses from all players

- Now, submit your guesses by emailing me at [cwiegand@uoregon.edu](mailto:cwiegand@uoregon.edu)

### Go!
:::{.f1}
```{r 2-3_avg}
#| echo: true
x_vec <- c( # class data
   89, 30, 23, 13.25, 17, 23, 38, 24, 30, 29,
   57, 31, 100, 99, 51.51, 84, 1, 34, 35, 38,
   10, 25, 20, 25, 50, 60, 16, 27, 8, 28,
   33, 14, 37, 63, 22, 25, 3, 38, 27, 26.67,
   33, 89, 50, 14, 11, 66
)

x_bar <- mean(x_vec)

tar <- (2 / 3) * x_bar
tar
```
:::

\

- Large study (~19,000 participants) in Denmark yielded a target of 21.6

### 2/3 Average game, explained

Let's assume people have a long time to think about this, and are thinking very carefully. 

1. If everyone guessed $x_i = 100$, then $\overline{x}=100$, so $T=66.\bar{6}$
   - Therefore, there is no way that $T>66.6$, so no guess (under the context listed above) "should" be more than 66.6
2. We assume that our sample of agents knows this, so they eliminate the possibility of others guessing $x_i>66.6$
3. Now, if all $x_i$ guesses are $\le 66.6$, the maximum $\overline{x}=66.6$, so the maximum $T=\frac{2}{3}(66.6)\approx 44.4$
   - Again, we assume that agents are "smart" enough and have enough time to deduce this
   - Therefore, since agents know $x_i>66.6$ is unreasonable, no guess should be higher than 44.4
4. Now, repeat the logic encapsulated in steps [1.]{.hi} -- [3.]{.hi}
   - Everyone rules out $x_i>44.4\ \implies T$ is at most $\frac{2}{3}(44.4)\approx 29.6$   
   - Everyone rules out $x_i>29.6\ \implies T$ is at most $\frac{2}{3}(29.6)\approx 19.7$
   - ...etc 

### 2/3 Average game, explained

If we repeat this line of thinking _ad infinitum_, we get that the "optimal" guess^[optimal under our assumption about thoughtful agents]...

- ...is _0_

:::{.absolute bottom="15%"}
- This kind of thinking is where we are headed
:::


### What is a game?

What are some key components to a game?

:::{.absolute bottom="0"}
- There are three things that are essential to specifying a game:

1. Players
1. Strategies
1. Payoffs
:::

### Economics as a modeling discipline

- Common throughout all subfields of economics
   - metrics, micro, macro, trade, etc.

- Our models often have extreme generalizations and/or simplifications -- often times these are labelled _assumptions_
- these models help us understand some phenomena in a vacuum
- then you worry about adding frictions

### Mapmaker Example

- **On Exactitude in Science**

   - Jorge Luis Borges, Collected Fictions, translated by Andrew Hurley.

   > ...In that Empire, the Art of Cartography attained such Perfection that the map of a single Province occupied the entirety of a City, and the map of the Empire, the entirety of a Province. In time, those Unconscionable Maps no longer satisfied, and the Cartographers Guilds struck a Map of the Empire whose size was that of the Empire, and which coincided point for point with it. The following Generations, who were not so fond of the Study of Cartography as their Forebears had been, saw that that vast Map was Useless, and not without some Pitilessness was it, that they delivered it up to the Inclemencies of Sun and Winters. In the Deserts of the West, still today, there are Tattered Ruins of that Map, inhabited by Animals and Beggars; in all the Land there is no other Relic of the Disciplines of Geography.
   
   — Suarez Miranda,Viajes de varones prudentes, Libro IV,Cap. XLV, Lerida, 1658


